/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void Roll(){
        int[] numroll = {1,2,3,4,5,6};
        Boolean flagroll = false;

        Library classUnderTest = new Library();
        int[] testResult = classUnderTest.roll(3);

        assertEquals(3,testResult.length);
        test:
        for(int i = 0 ; i<3 ; i++)
        {
            for(int j = 0 ; j<numroll.length ; j++){
                if(testResult[i] == numroll[j]){
                    flagroll=true;
                    break;
                }
                flagroll = false;
            }
            if(flagroll == false){
                break test;
            }
        }
        if(!flagroll) {
            assertEquals("array contains only number from 1 to 6", testResult);
        }
    }
    @Test void DuplicateArray(){
        Library classUnderTest = new Library();
        Boolean testResult = classUnderTest.containsDuplicates(new int[]{1,2, 6, 7});
        assertEquals(false,testResult);
        Boolean testResult2 = classUnderTest.containsDuplicates(new int[]{1,2,2, 6, 7});
        assertEquals(true,testResult2);
    }

    @Test void AvgArray(){
        Library classUnderTest = new Library();
        double testResult = classUnderTest.Calculating_Averages(new double[]{1,2,1,1});
        assertEquals(1.25,testResult);
        double testResult2 = classUnderTest.Calculating_Averages(new double[]{1,2,2, 6, 7});
        assertEquals(3.6,testResult2);
    }

    @Test void LowestAvgArray(){
        Library classUnderTest = new Library();
        int[] testResult = classUnderTest.lowest_Average(new int[][]{
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        });
        assertArrayEquals(new int[]{55, 54, 60, 53, 59, 57, 61}, testResult);
        int[] testResult2 = classUnderTest.lowest_Average(new int[][]{
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {65, 56, 55, 52, 55, 62, 57}
        });
        assertArrayEquals(new int[]{65, 56, 55, 52, 55, 62, 57},testResult2);
    }
}
