/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {

        Resturant resturant1 = new Resturant("Mac",50);
        System.out.println(resturant1.toString());
        Review rev1 = new Review("Nice place","Alaa",5);
        resturant1.addReview(rev1);
        Review rev2 = new Review("Clean place","Yousef",4);
        resturant1.addReview(rev2);
        Review rev3= new Review("Nice place","Alaa",3); // Same Author
        resturant1.addReview(rev3);
//        Review rev3 = new Review("Nice place","Alaa",6);
//        resturant1.addReview(rev3);
        System.out.println(resturant1.toString());


        Resturant resturant2 = new Resturant("Res2",100);
        Review rev1_2 = new Review("clean","Baraa",4);
        resturant2.addReview(rev1_2);
        System.out.println(resturant2.toString());


    }
}
