/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

//    List<String> categories = asList("one", "two", "three");
//    assertTrue(myArraylist.equals(categories));
    @Test void FileTestNoError(){
        App classUnderTest = new App();
        ArrayList<String> Result = classUnderTest.ReadErrorFile("test1.js");
        assertEquals(0 , Result.size());
    }

    @Test void FileTestOneError(){
        App classUnderTest = new App();
        ArrayList<String> Result = classUnderTest.ReadErrorFile("test2.js");
        assertEquals(1 , Result.size());
    }
    @Test void FileTestFewError() {
        App classUnderTest = new App();
        ArrayList<String> Result = classUnderTest.ReadErrorFile("test3.js");

        assertTrue(Result.size() <= 5);
    }

        @Test void FileTestManyError(){
        App classUnderTest = new App();
        ArrayList<String> Result = classUnderTest.ReadErrorFile("test4.js");
        assertTrue(Result.size()>20);

        }

    @Test void FileTestEmpty(){
        App classUnderTest = new App();
        ArrayList<String> Result = classUnderTest.ReadErrorFile("test5.js");
        Boolean flag = false;
        if(Result.size() == 1 ){
            for (String str:
                 Result) {
                if(str == "Empty"){
                    flag = true;
                }
            }
        }
        assertEquals(true,flag);

    }
}
